sudo: false
language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
rvm:
  - 2.2.5
  - 2.4.0
before_install:
  - nvm install 6.0
before_script:
  - npm install -g yarn
script:
  - bundle exec rake test
